name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Debug - Print directory structure
      run: |
        pwd
        ls -R
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        cd bounty-hunter-todo/frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd bounty-hunter-todo/frontend
        npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    
    - name: Debug - Print directory structure
      run: |
        pwd
        ls -R
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        cd bounty-hunter-todo/frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd bounty-hunter-todo/frontend
        npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bounty-hunter-todo/frontend/dist