name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install dependencies
      run: |
        echo "@jeffreymjohnson:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        npm ci
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend
    
    - name: Build frontend
      run: npm run build
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install dependencies
      run: |
        echo "@jeffreymjohnson:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        npm ci
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend
    
    - name: Build frontend
      run: npm run build
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/bounty-hunter-todo/frontend/dist