name: CI/CD Pipeline

on:
  push: # this triggers the workflow when code is pushed to the repository
    branches: [ main ]
  pull_request: # this triggers the workflow when a pull request is opened or updated
    branches: [ main ]

jobs: # this is the list of jobs that will be run in the workflow
  build-and-test: # this is the name of the job
    runs-on: ubuntu-latest # this specifies the operating system that the job will run on

    steps:
    - uses: actions/checkout@v4 # this checks out the code in the repository
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install dependencies
      run: |
        echo "@jeffreymjohnson:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        npm ci
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend
    
    - name: Build frontend
      run: npm run build
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'
    
    - name: Install dependencies
      run: |
        echo "@jeffreymjohnson:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        npm ci
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend
    
    - name: Build frontend
      run: npm run build
      working-directory: ${{ github.workspace }}/bounty-hunter-todo/frontend
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/bounty-hunter-todo/frontend/dist