name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'bounty-hunter-todo/frontend/**'
      - '.github/workflows/docker-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      working-directory: ./bounty-hunter-todo/frontend

    - name: Build Docker image
      run: |
        pwd
        docker build --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -t ghcr.io/jeffreymjohnson/github-actions-demo:latest .
      working-directory: ./bounty-hunter-todo/frontend
  
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:latest
