name: NPM Publish Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'bounty-hunter-todo/npm-package/**'
      - '.github/workflows/npm-publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      working-directory: ./bounty-hunter-todo/npm-package

    - name: Bump version
      run: |
        npm version patch --no-git-tag-version
      working-directory: ./bounty-hunter-todo/npm-package

    - name: Commit version bump
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add ./bounty-hunter-todo/npm-package/package.json
        git commit -m "chore(release): bump version to $(node -p -e "require('./bounty-hunter-todo/npm-package/package.json').version")"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Authenticate with GitHub Packages
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_TOKEN }}" > ~/.npmrc
  
    - name: Build and publish package
      run: npm publish --access public
      working-directory: ./bounty-hunter-todo/npm-package
